name: Docker Buildx Bake
  # You may pin to the exact commit or the version.
  # uses: docker/bake-action@017aa056d6bfc9797de5a5dd354a209dc07b490e
  uses: docker/bake-action@v4.3.0
  with:
    # Builder instance
    builder: # optional
    # Context to build from. Can be either local or a remote bake definition
    source: # optional
    # List of bake definition files
    files: # optional
    # Working directory of bake execution
    workdir: # optional, default is .
    # List of bake targets
    targets: # optional
    # Do not use cache when building the image
    no-cache: # optional, default is false
    # Always attempt to pull a newer version of the image
    pull: # optional, default is false
    # Load is a shorthand for --set=*.output=type=docker
    load: # optional, default is false
    # Provenance is a shorthand for --set=*.attest=type=provenance
    provenance: # optional
    # Push is a shorthand for --set=*.output=type=registry
    push: # optional, default is false
    # SBOM is a shorthand for --set=*.attest=type=sbom
    sbom: # optional
    # List of targets values to override (eg. targetpattern.key=value)
    set: # optional
          
